version: '3.6'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432