version: '3.6'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - db
    restart: on-failure
    entrypoint: ["sh", "-c", "make run-migrations && ./server"]
