package events

const (
	// VENDOR INCOME EVENT
	CALCULATE_VENDOR_INCOME_EVENT = "CALCULATE_VENDOR_INCOME_EVENT"

	// ORDER EVENT
	CHANGED_ORDER_STATUS_EVENT = "CHANGED_ORDER_STATUS_EVENT"

	// PRODUCT EVENT
	PRODUCT_CREATED_EVENT  = "PRODUCT_CREATED_EVENT"
	PRODUCT_VERIFIED_EVENT = "PRODUCT_VERIFIED_EVENT"

	// USER EVENT
	USER_REGISTERED_EVENT       = "USER_REGISTERED_EVENT"
	USER_VERIFIED_EVENT         = "USER_VERIFIED_EVENT"
	USER_COMPLETE_PROFILE_EVENT = "USER_COMPLETE_PROFILE_EVENT"
)
